services:
  backend:
    image: bonaca-backend:0.0.1-SNAPSHOT
    container_name: bonaca-backend
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: remote-dev
    ports:
      - "8090:8080"
    networks:
      - infrastructure
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

networks:
  infrastructure:
    external: true
    name: infrastructure_default
